version: '3.8'
services:
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./config:/mosquitto/config/
    ports:
      - '1883:1883'
    restart: unless-stopped
  
  delegator:
    build: ./delegator
    depends_on:
      - mosquitto

  sensor_a:
    build: ./sensor_a
    depends_on:
      - mosquitto
      - delegator
  
  sensor_b:
    build: ./sensor_b
    depends_on:
      - mosquitto
      - delegator
  